evidencia1/Models/producto_imagen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evidencia1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_imagen
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public int id_producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}

evidencia1/Controllers/Producto_imagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using evidencia1.Models;
using System.IO;

namespace evidencia1.Controllers
{
    public class Producto_imagenController : Controller
    {
        // GET: Producto_imagen
        public ActionResult Index()
        {
            using (var db = new inventario_2021Entities2())
            {
                return View(db.producto_imagen.ToList());
            }

        }

        public static string NombreProducto(int idproducto)
        {
            using (var db = new inventario_2021Entities2())
            {
                return db.producto.Find(idproducto).nombre;
            }
        }

        public ActionResult ListarProducto()
        {
            using (var db = new inventario_2021Entities2())
            {
                return PartialView(db.producto.ToList());
            }
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto_imagen producto_Imagen)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var db = new inventario_2021Entities2())
                {
                    db.producto_imagen.Add(producto_Imagen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventario_2021Entities2())
            {
                return View(db.producto_imagen.Find(id));
            }
        }

        public ActionResult Edit(int id)
        {
            using (var db = new inventario_2021Entities2())
            {
                producto_imagen productoimagenEdit = db.producto_imagen.Where(a => a.id == id).FirstOrDefault();
                return View(productoimagenEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto_imagen productoimagenEdit)
        {
            try
            {
                using (var db = new inventario_2021Entities2())
                {
                    var oldproductoimagen = db.producto_imagen.Find(productoimagenEdit.id);
                    oldproductoimagen.imagen = productoimagenEdit.imagen;
                    oldproductoimagen.id_producto = productoimagenEdit.id_producto;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario_2021Entities2())
                {
                    producto_imagen producto_imagen = db.producto_imagen.Find(id);
                    db.producto_imagen.Remove(producto_imagen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult CargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CargarImagen(int producto, HttpPostedFileBase imagen)
        {
            try
            {
                
                string filePath = string.Empty;
                string nameFile = "";

                
                if (imagen != null)
                {
                    string path = Server.MapPath("~/Uploads/Imagenes/");

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    nameFile = Path.GetFileName(imagen.FileName);

                    filePath = path + Path.GetFileName(imagen.FileName);

                    string extension = Path.GetExtension(imagen.FileName);

                    imagen.SaveAs(filePath);
                }

                using (var db = new inventario_2021Entities2())
                {
                    var producto_Imagen = new producto_imagen();
                    producto_Imagen.id_producto = producto;
                    producto_Imagen.imagen = "/Uploads/Imagenes/" + nameFile;
                    db.producto_imagen.Add(producto_Imagen);
                    db.SaveChanges();

                }

                return View();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
    }
}
        
    

evidencia1/Views/Producto_imagen/CargarImagen.cshtml
<h2>Cargar Imagen Producto</h2>

@using (Html.BeginForm("CargarImagen", "Producto_imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label col-md-2" for="id_producto">Lista productos</label>
        <div class="col-md-10">
          <input type="number" name="producto" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Imagen</label>
        <div class="col-md-10">
            <input type="file" name="imagen" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Enviar" class="form-control" />
        </div>
    </div>

}

evidencia1/Views/Producto_imagen/Create.cshtml
@model evidencia1.Models.producto_imagen

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>producto_imagen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2" for="id">Imagen</label>
        @*@Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="id">producto</label>
            @*@Html.LabelFor(model => model.id_producto, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.Action("ListarProducto")
            @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
        </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

evidencia1/Views/Producto_imagen/Details.cshtml
@model evidencia1.Models.producto_imagen

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>producto_imagen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imagen:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            Producto:
        </dt>

        <dd>
            @evidencia1.Controllers.Producto_imagenController.NombreProducto(Model.id_producto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Regresar", "Index")
</p>

evidencia1/Views/Producto_imagen/Edit.cshtml
@model evidencia1.Models.producto_imagen

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>producto_imagen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

    <div class="form-group">
        <label class="control-label col-md-2" for="id">Imagen</label>
        @*@Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="id">Producto</label>
        @*@Html.LabelFor(model => model.id_producto, htmlAttributes: new { @class = "control-label col-md-2" })*@
    <div class="col-md-10">
        @Html.Action("ListarProducto")
        @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
    </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

evidencia1/Views/Producto_imagen/Index.cshtml
@model IEnumerable<evidencia1.Models.producto_imagen>

@{
    ViewBag.Title = "Producto_Imagen";
}

<h2>Producto_Imagen</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Imagen:
        </th>
        <th>
            Producto:
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.imagen)
            </td>
            <td>
                @evidencia1.Controllers.Producto_imagenController.NombreProducto(item.id_producto)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.id }, new { @class = "linkDelete" })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("subir imagen", "CargarImagen")
@section scripts{
    <script>
        $(".linkDelete").click(function (event) {
            if (!confirm('¿Esta seguro de eliminar?')) {
                event.preventDefault();
            }
        })
    </script>
}

evidencia1/Views/Producto_imagen/ListarProducto.cshtml
@model IEnumerable<evidencia1.Models.producto>

<select class="form-control" id="id_producto" name="id_producto">
    @foreach (var item in Model)
    {
        <option value="@item.id">@item.nombre</option>
    }
</select>